---
title: "Assignment1_econometrics_Malenesr-and-Raojiaxiu"
format: html
# documentclass: article
classoption: 
  - '12pt'
  - 'a4paper'
author: 
  - name: Malene Skurtveit Rossnes
    affiliation: 'Master Student HVL'
  - name: Jiaxiu Rao
    affiliation: 'Master Student HVL'
editor: visual
# bibliography: [.bib]
csl: apa-no-ampersand.csl
abstract: 'This'
---

## 

```{r}
#library(readr)
#library(ggplot2)
library(tidyverse)
library(vtable)
#library(dplyr)

# read data from files
gdpfile <- read_csv('NAMA_10R_3GDP.csv')
populationfile <- read_csv('DEMO_R_PJANAGGR3.csv')

gdpdata <- gdpfile %>%
  rename(Year = TIME_PERIOD, GDP = OBS_VALUE, Country=geo)

populationdata <- populationfile %>%
  rename(Year = TIME_PERIOD, Population = OBS_VALUE, Country = geo)

gdpdata <- gdpdata %>%
  # select only columns we need
  select(Year, Country, GDP, unit) %>%
  # select rows with MIO_EUR and the countries we need
  filter(unit =='MIO_EUR' & Country %in% c('DE', 'FI', 'RO'))

mydata <- gdpdata %>%
  # combine gdpr data with population data with the same year and country
  left_join(populationdata, by=c("Year","Country"),
            suffix = c("","_population")) %>%
   # only rows with TOTAL and T from the population data
  filter(age=='TOTAL' & sex=='T')

mydata <- mydata %>% 
  # select the fields that we need
  select(Year, Country, GDP,Population) %>%
  mutate(GDPpercapita = 1000000 * GDP / Population) 
```

Germany:
```{r}
mydata %>%
  filter(Country=='DE') %>%
  select(-Country) %>%
  vtable::st(.)
```

Finland:
```{r}

mydata %>%
  filter(Country=='FI') %>%
  select(-Country) %>%
  vtable::st(.)
```

Romania:
```{r}
mydata %>%
  filter(Country=='RO') %>%
  select(-Country) %>%
  vtable::st(.)
```


```{r}
  ggplot(mydata, aes(x = Year, y=GDPpercapita, fill=Country, color=Country)) +
  geom_line(lwd = .8) +
   labs(x = "Year", y = "GDP per capita")
```

